import localFont from "next/font/local";
import "./globals.css";
import { NextUIProvider } from '@nextui-org/react'
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextUIProvider>
          <header className="bg-[#fffff5] shadow-lg shadow-[#FAF6E6] rounded-b-3xl flex justify-center items-center">
            <img
              src="/logo-rm.png"
              alt="Logo"
              className="h-20"
            />
          </header>

          <ToastContainer />
          {children}
        </NextUIProvider>
      </body>
    </html>
  );
}
